### PR TITLE
Merge main into pdb pt2

### PR DESCRIPTION
**Pull request by Swiftb0y**
CI is obviously still broken but at least this branch is now up to date and warning-free again so somebody can work on fixing it.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks, but the branch contains unfinished WIP commits that I don't want to end up in the git history of the main branch, so I think merging main is not the best option here. I rebased the branch on latest main instead.

**Comment by Swiftb0y** [comment]
Can you elaborate? this PR did exactly that. Merging `main` into `pdb-serialization-pt2`, not the other way around. I issued this in PR form since I had to resolve some merge conflicts and I obviously also don't have the access to push to your branch.

**Comment by Holzhaus** [comment]
It's basically impossible to amend the "WIP" commit (6a7e25d) once this PR would have been merged (due to the merge commit 3e89dd6 that comes after), which means there would be a broken WIP commit in `main`'s git history if we ever merge the `pdb-serialization-pt2` branch into `main` at some point.

**Comment by Swiftb0y** [comment]
Ok that makes sense. Thanks for taking care of rebasing then. Just out of curiosity: Why wouldn't fixups of the WIP commits not work?

**Comment by Holzhaus** [comment]
Rebasing with merge commits is messy because they have two parents. It might be possible but any time I tired it I found it cumbersome and just rebasing turned out the better option ;-)

**Comment by Swiftb0y** [comment]
Great. thanks for the wisdom. :+1:

**Comment by Holzhaus** [comment]
> Great. thanks for the wisdom. +1

`s/wisdom/incompetence when dealing with merge commits/` :wink:

**Pull request closed without merging**
